{
 "title": "API Gateway",
 "description": "AWS API Gateway",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" },
   { "name": "region", "query": "regions()" },
   {
    "name": "api",
    "query": "dimension_values($region, AWS/ApiGateway, Count, ApiName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ApiName": "$api" },
     "id": "total",
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ApiName": "$api" },
     "id": "error4xx",
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ApiName": "$api" },
     "id": "error5xx",
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "Error Rate %",
     "expression": "SUM([error4xx, error5xx]) *100/total",
     "id": "error",
     "metricEditorMode": 1,
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Cache Hit vs Miss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ApiName": "$api" },
     "metricName": "CacheHitCount",
     "namespace": "AWS/ApiGateway",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ApiName": "$api" },
     "metricName": "CacheMissCount",
     "namespace": "AWS/ApiGateway",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "dimensions": { "ApiName": "$api" },
     "metricName": "IntegrationLatency",
     "namespace": "AWS/ApiGateway",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ApiName": "$api" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "\n<a href=\"https://github.com/praveenchandran/grafana\" target=\"_blank\"/>Github Repo</a> | \n<a target=\"_blank\" href=\"https://github.com/praveenchandran\">Author</a> |\n<a target=\"_blank\" href=\"https://grafana.com/dashboards/16206\">Download link</a> |\n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-metrics-and-dimensions.html\">AWS Cloudwatch documentation</a>"
   }
  }
 ]
}