{
 "title": "Amazon MQ",
 "description": "Amazon MQ metrics for Active MQ",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "broker",
    "query": "dimension_values($region, AWS/AmazonMQ, CpuUtilization, Broker)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Messages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "TotalMessageCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Total Producers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "TotalProducerCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Total Consumers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "TotalConsumerCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Broker Storage Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "StorePercentUsage",
     "namespace": "AWS/AmazonMQ",
     "period": "5m",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Broker Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "TotalMessageCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "TotalEnqueueCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "TotalDequeueCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Messages by Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker": "$broker", "Queue": "*" },
     "metricName": "QueueSize",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Dequeue Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker": "$broker", "Queue": "*" },
     "metricName": "DequeueCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Consumers by Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker": "$broker", "Queue": "*" },
     "metricName": "ConsumerCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Producers by Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker": "$broker", "Queue": "*" },
     "metricName": "ProducerCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Consumers vs Producers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "TotalConsumerCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "TotalProducerCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Connections vs Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "CurrentConnectionsCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "EstablishedConnectionsCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "OpenTransactionCount",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Broker CPU and Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "CpuUtilization",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "HeapUsage",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "MemoryUsage",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "BurstBalance",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Broker Network usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "NetworkIn",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "Broker": "$broker" },
     "metricName": "NetworkOut",
     "namespace": "AWS/AmazonMQ",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "\n<a href=\"https://github.com/praveenchandran/grafana\" target=\"_blank\"/>Github Repo</a> | \n<a target=\"_blank\" href=\"https://github.com/praveenchandran\">Author</a> |\n<a target=\"_blank\" href=\"https://grafana.com/dashboards/123\">Download link</a> |\n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/security-logging-monitoring-cloudwatch.html\">AWS Cloudwatch documentation</a>"
   }
  }
 ]
}