{
 "title": "AWS Transit Gateway",
 "description": "AWS Transit Gateway metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "gateway",
    "label": "Transit Gateway Id",
    "query": "dimension_values($region, AWS/TransitGateway, BytesIn, TransitGateway)"
   },
   {
    "name": "attachmentId",
    "label": "Transit Gateway attachment Id",
    "query": "dimension_values($region, AWS/TransitGateway, BytesIn, TransitGatewayAttachment, {\"TransitGateway\": \"$gateway\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Gateway Byte Transfer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": { "TransitGateway": "$gateway" },
     "metricName": "BytesIn",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TransitGateway": "$gateway" },
     "metricName": "BytesOut",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Gateway Attachment Byte Transfer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": {
      "TransitGateway": "$gateway",
      "TransitGatewayAttachment": "$attachmentId"
     },
     "metricName": "BytesIn",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "TransitGateway": "$gateway",
      "TransitGatewayAttachment": "$attachmentId"
     },
     "metricName": "BytesOut",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Gateway Packet Transfer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "TransitGateway": "$gateway" },
     "metricName": "PacketsIn",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TransitGateway": "$gateway" },
     "metricName": "PacketsOut",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Gateway Attachment  Packet Transfer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "TransitGateway": "$gateway",
      "TransitGatewayAttachment": "$attachmentId"
     },
     "metricName": "PacketsIn",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "TransitGateway": "$gateway",
      "TransitGatewayAttachment": "$attachmentId"
     },
     "metricName": "PacketsOut",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Gateway Bytes Dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": { "TransitGateway": "$gateway" },
     "metricName": "BytesDropCountBlackhole",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TransitGateway": "$gateway" },
     "metricName": "BytesDropCountNoRoute",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Gateway Attachment Bytes Dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": {
      "TransitGateway": "$gateway",
      "TransitGatewayAttachment": "$attachmentId"
     },
     "metricName": "BytesDropCountBlackhole",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "TransitGateway": "$gateway",
      "TransitGatewayAttachment": "$attachmentId"
     },
     "metricName": "BytesDropCountNoRoute",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Gateway Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "TransitGateway": "$gateway" },
     "metricName": "PacketDropCountBlackhole",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TransitGateway": "$gateway" },
     "metricName": "PacketDropCountNoRoute",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Gateway Attachment Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "TransitGateway": "$gateway",
      "TransitGatewayAttachment": "$attachmentId"
     },
     "metricName": "PacketDropCountBlackhole",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "TransitGateway": "$gateway",
      "TransitGatewayAttachment": "$attachmentId"
     },
     "metricName": "PacketDropCountNoRoute",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "\n<a href=\"https://github.com/praveenchandran/grafana\" target=\"_blank\"/>Github Repo</a> | \n<a target=\"_blank\" href=\"https://github.com/praveenchandran\">Author</a> |\n<a target=\"_blank\" href=\"https://grafana.com/dashboards/16196\">Download link</a> |\n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/vpc/latest/tgw/transit-gateway-cloudwatch-metrics.html\">AWS Cloudwatch documentation</a>"
   }
  }
 ]
}